name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: "**"

jobs:
  ubuntu-latest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.10]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Copy .env file
        run: cp .env.example .env
      - run: npm install
      - run: npx hardhat compile

  macos-latest:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [20.10]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Mock .env file
        run: cp .env.example .env
      - run: npm install
      - run: npx hardhat compile

  windows-latest:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [20.10]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Mock .env file
        run: copy .env.example .env
      - run: npm install
      - run: npx hardhat compile
