name: coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: "**"

jobs:
  coverage:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 20.10
        uses: actions/setup-node@v3
        with:
          node-version: 20.10
          cache: 'npm'

      - name: Copy .env file
        run: cp .env.example .env

      - name: Install dependencies
      - run: npm install

      - name: Run tests with coverage
      - run: npx hardhat coverage

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
