name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: "**"

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [20.10]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Copy .env file
        run: cp .env.example .env

      - run: npm install

      - run: npx hardhat test
